[3132][ADD] sale_order_subject
qrtl/fal-custom pull request #12
Opened 2023-01-27 10:38 UTC by rinaldifirdaus

[3132](https://www.quartile.co/web?db=quartile&token=dMRr78CMkEX6gyy9nTiv#id=3132&action=771&model=project.task&view_type=form&menu_id=505)

Add subject fields into the sale order

2023-01-30 09:59 UTC, yostashiro requested changes

2023-01-30 09:59 UTC, yostashiro commented on sale_order_subject/__manifest__.py
> +    "depends": ["sale"],
```suggestion
    "depends": ["sale", "account_move_subject"],
```

2023-01-30 10:12 UTC, yostashiro approved these changes

2023-12-05 06:11 UTC, AungKoKoLin1997 approved these changes

2025-06-19 03:00 UTC, kanda999 commented
Close PR as this module is no longer in use.

2025-06-19 03:00 UTC, closed without merging