[3221][ADD] account_move_duplicate_ref
qrtl/fal-custom pull request #21
Opened 2023-06-19 08:51 UTC by rinaldifirdaus

[3221](https://www.quartile.co/web?db=quartile&token=dMRr78CMkEX6gyy9nTiv#id=3221&action=771&model=project.task&view_type=form&menu_id=505)

2023-06-19 09:46 UTC, yostashiro requested changes
Can we rename the module to `account_move_ref_duplicatable`?

2023-06-19 09:46 UTC, yostashiro commented on account_move_duplicate_ref/models/account_move.py
@rinaldifirdaus I was thinking that we would need this, but is it not the case?
```
    ref = fields.Char(copy=True)
```

2023-06-19 09:46 UTC, yostashiro commented on account_move_duplicate_ref/models/account_move.py
> +        return super(AccountMove, self).copy(default=default)
```suggestion
        return super().copy(default=default)
```

2023-06-19 09:46 UTC, yostashiro commented on account_move_duplicate_ref/models/account_move.py
> +    _inherit = ["account.move"]
```suggestion
    _inherit = "account.move"
```

2023-06-19 10:08 UTC, rinaldifirdaus commented on account_move_duplicate_ref/models/account_move.py
With current code, i've tested that even we don't add "ref = fields.Char(copy=True)" the value was properly copied, Tashiro san.

2023-06-21 08:40 UTC, rinaldifirdaus commented
@yostashiro could you please help to merge this PR? client has confirm that we can install this to production. Thank you

2023-06-21 08:42 UTC, yostashiro approved these changes

2023-06-21 08:42 UTC, merged