[3006][ADD] report_qweb_decimal_place
qrtl/fal-custom pull request #4
Opened 2022-12-20 08:59 UTC by AungKoKoLin1997

[3006](https://www.quartile.co/web#id=3006&action=771&model=project.task&view_type=form&menu_id=505)

2023-01-03 10:28 UTC, kakurai8 reviewed
I checked the current status.
(Settings is added, but this module alone doesn't work.)
![report_qweb_decimal_place](https://user-images.githubusercontent.com/80655511/210339731-54829b3d-ad02-4a09-9ebe-51e3b18c3728.png)

2023-01-03 10:32 UTC, AungKoKoLin1997 commented
@kakurai8 This module alone will not work. This module is for base configuration and we need to use with other modules(sale_report_qweb_decimal_places, etcs). I am waiting Yoshi's approval and will continue working on another modules.

2023-01-03 13:15 UTC, yostashiro requested changes

2023-01-03 13:15 UTC, yostashiro commented on report_qweb_decimal_place/readme/DESCRIPTION.rst
> +-----------
```suggestion
~~~~~~~~~~~

```
See https://github.com/OCA/maintainer-tools/pull/455#issuecomment-636305924.

Please update the OCA PR as well.

2023-01-04 02:50 UTC, yostashiro requested changes

2023-01-04 02:50 UTC, yostashiro commented on report_qweb_decimal_place/readme/DESCRIPTION.rst
> +~~~~~~~~~~~
```suggestion
~~~~~~~~~~~

```
Please pay attention to the suggested blank line!

2023-01-04 03:05 UTC, yostashiro commented on report_qweb_decimal_place/README.rst
> + - Define decimal place in price_decimal_place field
```suggestion
To apply price unit format:

#. Go to Invoicing --> Configuration --> Currencies
#. Check apply_price_decimal_place field
#. Define decimal place in price_decimal_place field
```

2023-01-04 15:35 UTC, yostashiro approved these changes

2023-01-17 07:28 UTC, yostashiro commented
This module should be added in fal-oca.

2023-01-28 14:43 UTC, yostashiro commented
Superseded by https://github.com/qrtl/fal-oca/pull/9.

2023-01-28 14:43 UTC, closed without merging